version: "3.8"

services:
  nestapp:
    build: ./
    ports:
      - "3001:3001"
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgresradioticket
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  pgdata: